version: '3.8'

services:
  pocketbase:
    container_name: pocketbase
    build: .
    image: pocketbase:latest
    volumes:
      - pocketbase-volume-data:/app/pocketbase/pb_data
      - pocketbase-volume-migrations:/app/pocketabse/pb_migrations
    networks:
      - my-network
    ports:
      - "8090:8090"

networks:
  my-network:
    name: my-network

volumes:
  pocketbase-volume-data:
    name: pocketbase-volume-data
  pocketbase-volume-migrations:
    name: pocketbase-volume-migrations
